"use client";
import { useState } from "react";
import { Eye, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useRegulators } from "@/hooks/organizations";
import { useRegulatoryAuthorities } from "@/hooks/regulatory-authorities";
import { useGrantRegulatoryOversightScope, useRegulatoryOversightScopes, useRevokeRegulatoryOversightScope } from "@/hooks/regulatory-oversight-config";

export function OversightScopeSettings() {
  const { data: scopes = [] } = useRegulatoryOversightScopes(); const { data: organizations = [] } = useRegulators(); const { data: authorities = [] } = useRegulatoryAuthorities();
  const grant = useGrantRegulatoryOversightScope(); const revoke = useRevokeRegulatoryOversightScope(); const [organizationId, setOrganizationId] = useState(""); const [authorityId, setAuthorityId] = useState("");
  return <Card><CardHeader><CardTitle className="text-base">Oversight scopes</CardTitle><CardDescription>Choose which configured authorities an oversight organization may observe. This does not grant access to individual cases.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><select aria-label="Oversight organization" className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={organizationId} onChange={(event) => setOrganizationId(event.target.value)}><option value="">Choose oversight organization</option>{organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select><select aria-label="Authority to observe" className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={authorityId} onChange={(event) => setAuthorityId(event.target.value)}><option value="">Choose authority</option>{authorities.filter((authority) => authority.isActive).map((authority) => <option key={authority.id} value={authority.id}>{authority.name}</option>)}</select><Button disabled={!organizationId || !authorityId || grant.isPending} onClick={() => grant.mutate({ oversightOrganizationId: Number(organizationId), authorityId: Number(authorityId) }, { onSuccess: () => setAuthorityId("") })}>{grant.isPending ? "Granting…" : "Grant view"}</Button></div><div className="divide-y rounded-lg border border-border">{scopes.length === 0 ? <p className="p-4 text-sm text-muted-foreground">No oversight scopes configured.</p> : scopes.map((scope) => <div key={scope.id} className="flex items-center justify-between gap-3 p-4"><div><p className="text-sm font-medium">{scope.oversightOrganization.name}</p><p className="mt-1 text-xs text-muted-foreground">Can observe {scope.authority.name} · {scope.authority.code}</p></div><Button size="icon" variant="ghost" aria-label="Remove oversight scope" disabled={revoke.isPending} onClick={() => revoke.mutate(scope.id)}><Trash2 className="size-4 text-danger" /></Button></div>)}</div></CardContent></Card>;
}
